sonata_seo:
  encoding: UTF-8
  page:
    title: 'MuseGO'
    # title_prefix:  'Prefix |'
    # title_suffix:  '| Suffix'
    default: sonata.seo.page.default
    metas:
      name:
        keywords: Tunis, Tunisie, Ariana, Art, Histoire, Expositions, Collections, Éducation, Visites guidées, Galerie d'art, Sculpture, Peinture, Art, contemporain, Patrimoine, culturel, Archéologie, Anthropologie, Sciences naturelles, Musique, Cinéma, Théâtre, Ateliers, Conférences, Événements, Programme pour enfants, Tourisme, Billetterie
        description: Notre musée est un lieu de rencontre et de découverte pour les visiteurs de tout âge. Nous sommes fiers de mettre en valeur des objets remarquables qui racontent l'histoire
          de notre monde, de notre société et de notre culture.
        robots: index, follow

      property:
        # Facebook application settings
        #'fb:app_id':          XXXXXX
        #'fb:admins':          admin1, admin2

        # Open Graph information
        # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
        'og:site_name': MuseGO
        'og:description': Notre musée est un lieu de rencontre et de découverte pour les visiteurs de tous âges
          et de tous horizons. Nous sommes fiers de mettre en valeur des objets remarquables qui racontent l'histoire
          de notre monde, de notre société et de notre culture. Nous sommes également engagés dans la promotion
          de l'art contemporain et dans la reconnaissance des artistes locaux.
        'og:local': fr_FR
        'og:image': https://musego.tn/images/poster1000.png
      #
      #      http-equiv:
      #        'Content-Type': text/html; charset=utf-8
      #        #'X-Ua-Compatible':      IE=EmulateIE7

      charset:
        UTF-8: ''

    head:
      'xmlns': http://www.w3.org/1999/xhtml
      'xmlns:og': http://opengraphprotocol.org/schema/
      #'xmlns:fb':           "http://www.facebook.com/2008/fbml"